[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run worker:simple-test"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "payment-worker"
type = "worker"

[services.payment-worker]
startCommand = "npm run worker:simple-test" 