[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

# Pass environment variables to Docker build
[build.args]
SUPABASE_URL = "$SUPABASE_URL"
SUPABASE_SERVICE_KEY = "$SUPABASE_SERVICE_KEY"
DATABASE_URL = "$DATABASE_URL"
REDIS_URL = "$REDIS_URL"
WHATSAPP_API_URL = "$WHATSAPP_API_URL"
WHATSAPP_API_TOKEN = "$WHATSAPP_API_TOKEN"
SLACK_WEBHOOK_URL = "$SLACK_WEBHOOK_URL"
FRONTEND_URL = "$FRONTEND_URL"
NEXTAUTH_URL = "$NEXTAUTH_URL"
NEXTAUTH_SECRET = "$NEXTAUTH_SECRET"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 3
restartPolicyType = "always" 