[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start"

[staticAssets]
"public" = "./"

# Force cache invalidation
[buildCache]
clearCache = true 