-- Create a table to store merchant credentials, including their Easebuzz keys and the generated Lightspeed keys.
CREATE TABLE
  public.merchant_credentials (
    id UUID NOT NULL DEFAULT gen_random_uuid (),
    company_name TEXT NULL,
    lightspeed_client_key TEXT NOT NULL UNIQUE,
    lightspeed_client_salt TEXT NOT NULL,
    webhook_url TEXT NOT NULL UNIQUE,
    easebuzz_key TEXT NULL,
    easebuzz_salt TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT merchant_credentials_pkey PRIMARY KEY (id)
  );

-- Add comments to the table and columns for better understanding.
COMMENT ON TABLE public.merchant_credentials IS 'Stores credentials for merchants, including their Easebuzz configuration and the generated Lightspeed keys.';
COMMENT ON COLUMN public.merchant_credentials.company_name IS 'The name of the merchant''s company.';
COMMENT ON COLUMN public.merchant_credentials.lightspeed_client_key IS 'The unique client key generated by Lightspeed for the merchant.';
COMMENT ON COLUMN public.merchant_credentials.lightspeed_client_salt IS 'The unique client salt generated by Lightspeed for the merchant.';
COMMENT ON COLUMN public.merchant_credentials.webhook_url IS 'The unique webhook URL generated for the merchant to receive payment status updates.';
COMMENT ON COLUMN public.merchant_credentials.easebuzz_key IS 'The merchant''s API key for the Easebuzz payment gateway.';
COMMENT ON COLUMN public.merchant_credentials.easebuzz_salt IS 'The merchant''s API salt for the Easebuzz payment gateway.'; 