name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: lightspeedpay-integrated

      - name: Lint
        run: npm run lint --if-present
        working-directory: lightspeedpay-integrated

      - name: Run unit tests with coverage (Jest)
        run: npm run test:coverage
        working-directory: lightspeedpay-integrated

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: lightspeedpay-integrated/coverage

      # Upload coverage to Codecov for coverage tracking and PR status checks
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Set in repository secrets
          files: lightspeedpay-integrated/coverage/lcov.info
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true

      # Ensure Codecov branch protection rule (≥ 80 % project) is enforced on main
      - name: Enforce Codecov branch protection
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL_NAME: ${{ github.repository }}
          PROTECTED_BRANCH: main
        run: node scripts/enforce-codecov.js
        working-directory: lightspeedpay-integrated

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: lightspeedpay-integrated

      - name: Run E2E tests (Playwright)
        env:
          PLAYWRIGHT_E2E: '1'
          # The following secrets should be configured in repo settings for authenticated tests
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: npm run test:e2e
        working-directory: lightspeedpay-integrated 